[feature] Floating-Point Reductions
pulp-platform/ara pull request #131
Opened 2022-08-03 20:18 UTC by mp-17

WIP PR

## Changelog

### Fixed

- Description of changes

### Added

- Description of changes

### Changed

- Description of changes

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed
- [ ] No frequency degradation

2022-08-26 16:27 UTC, mp-17 commented
@suehtamacv: this is the next PR to merge :P

2022-09-01 13:21 UTC, suehtamacv requested changes
How well does this synthesize? Any report?

2022-09-01 13:21 UTC, suehtamacv commented on hardware/src/lane/operand_queue.sv
> +  assign lane_id_0 = lane_id_i == '0;
Hmm, I think I reviewed this already, and I asked you to just remove this logic assignment. But I think the comment survived. Can you remove this `logic` and the corresponding comment?

2022-09-01 13:21 UTC, suehtamacv commented on hardware/src/lane/vmfpu.sv
See previous comment.

2022-09-01 13:21 UTC, suehtamacv commented on hardware/src/lane/vmfpu.sv
> +  endfunction : next_mfpu_state
How well does this synthesize? It is not the usual way to write FSMs.

2022-09-01 13:21 UTC, suehtamacv commented on hardware/src/lane/vmfpu.sv
> +      //endcase
Just remove the logic!

2022-09-01 22:43 UTC, mp-17 commented
> How well does this synthesize? Any report?

Only synthesis? The whole flow is fine!

2022-09-01 22:49 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +  endfunction : next_mfpu_state
Do you think it can be problematic? Think that the tool just replace the function call with the conditional code inside the function. If so, why is it unconventional?

2022-09-02 20:14 UTC, mp-17 commented
DO NOT MERGE THIS INTO MAIN. 
Wait @suehtamacv, I need to fix this. I did not realize that `fmatmul` performance dropped... BTW, we really need an automated way to tell if we had performance regressions in terms of throughput.

2022-09-20 08:04 UTC, mp-17 commented
The problem is solved, I am just waiting for the backend run after the last fix.

2022-09-21 08:52 UTC, mp-17 commented
Solved, we can merge

2022-09-22 06:59 UTC, merged