Add support for vector fixed-point instructions
pulp-platform/ara pull request #147
Opened 2022-09-28 15:54 UTC by M-Ijaz-10x

Add support for `vssra`, `vssrl`, `vnclip`, `vnclipu` and `vsmul` vector fixed-point instructions

## Changelog

### Fixed

- N/A

### Added

- Support for vector single-width fractional multiply with rounding and saturation instruction: `vsmul`
- Support for vector single-width scaling shift instructions: `vssra`, `vssrl`
- Support for vector narrowing fixed-point clip instructions: `vnclip`, `vnclipu`
- Test for `vnclip` and `vnclipu` vector fixed-point instructions

### Changed

- Updated tests for `vssra`, `vssrl` and `vsmul` vector fixed-point instructions

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-10-05 20:17 UTC, mp-17 commented
Thanks a lot for the great work, I will review it tomorrow! 
In the meantime, I am checking that we have no frequency degradation.

Best,
Matteo

2022-10-11 08:33 UTC, mp-17 commented
I found some issues in integrating everything with the current lane size (over-utilization during placement), so I am exploring new lane sizes to host the changes! Ara is getting big! :-)

2022-10-18 13:17 UTC, mp-17 requested changes
Thanks a lot for the big work!

I have only one comment and a request.
The `vsmul` instruction uses SIMD multipliers that already exist in the VMFPU unit. 
We can make `vsmul` re-use them to avoid logic duplication.
This would also allow to close timing without frequency degradation, as the VALU expects all the instructions to finish in only 1 cycle.

2022-10-18 13:17 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +        VSMUL: unique case (vew_i)
I think that this is the cause of the huge Area increase.
This instruction seems to be better handled by the SIMD multipliers in the VMFPU module.
There, we can merge the multiplier logic with the already existing one, and add pipeline registers if needed.

2022-10-26 07:04 UTC, M-Ijaz-10x commented on hardware/src/lane/simd_alu.sv
> +        VSMUL: unique case (vew_i)
I have made the required changes, kindly review them. Thanks!

2022-10-26 07:51 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +        VSMUL: unique case (vew_i)
Thanks a lot, I will review it today!

2022-10-26 16:35 UTC, mp-17 commented
I am implementing the new hardware with our flow! I will let you know as soon as it's over! ;-)

2022-10-26 19:08 UTC, mp-17 commented
I see that the `vnclip` test is failing: https://github.com/pulp-platform/ara/actions/runs/3299234519/jobs/5509944124#step:8:21

2022-10-26 19:40 UTC, mp-17 requested changes
Thanks for the changes. I am running the flow on the new hardware. 
I enabled the CI and I see that one of the tests is failing (`vnclip` on Ara: 
https://github.com/pulp-platform/ara/actions/runs/3299234519/jobs/5509944124#step:8:21). 
Can you please have a look at it?

2022-10-26 19:40 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +  alu_vxsat_t  mfpu_vxsat;
This signal is multiply driven ^

2022-10-26 19:51 UTC, mp-17 requested changes

2022-10-26 19:51 UTC, mp-17 commented on hardware/src/ara_dispatcher.sv
> +    vxsat_d      = vxsat_q;
`vxrm_d` is never initialized ^

2022-10-26 20:15 UTC, mp-17 requested changes

2022-10-27 14:37 UTC, mp-17 requested changes

2022-10-27 14:37 UTC, mp-17 commented on hardware/src/lane/simd_mul.sv
> +  assign vxsat_o = vxsat;
I think we should break this path for the flag as we do here: https://github.com/pulp-platform/ara/blob/main/hardware/src/lane/vmfpu.sv#L911
Otherwise it can become critical

2022-10-27 14:37 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +  assign vxsat_o = vxsat;
I think we should break the path for the flag as we do here: https://github.com/pulp-platform/ara/blob/main/hardware/src/lane/vmfpu.sv#L911
Otherwise it can become critical

2022-10-27 18:31 UTC, mp-17 requested changes

2022-10-27 18:31 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +                res.w8 [2*b + narrowing_select_i] = $signed(opb.w16[b]) >>> opa.w16[b][3:0] + r;
For all the `vew_i`, better to replace

`res.w8 [2*b + narrowing_select_i] = $signed(opb.w16[b]) >>> opa.w16[b][3:0] + r;`

with

`res.w8 [2*b + narrowing_select_i] = ($signed(opb.w16[b]) >>> opa.w16[b][3:0]) + r;`

or

`res.w8 [2*b + narrowing_select_i] = clip + r;`

since the `+` is evaluated before the shift.

2022-10-27 18:31 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +                res.w8 [2*b + narrowing_select_i] = opb.w16[b] >> opa.w16[b][3:0] + r;
Same as before: enforce the ordering of the shift and sum operations for all the `vew_i`

2022-10-27 19:10 UTC, mp-17 requested changes

2022-10-27 19:10 UTC, mp-17 commented on hardware/src/ara_dispatcher.sv
> +                  6'b101110: ara_req_d.op = ara_pkg::VNCLIPU;
For all the `VNCLIP*` entries, we also need to tell that `eew_vs2` is greater than `vsew`:

`ara_req_d.eew_vs2 = vtype_q.vsew.next();`

Like:

```verilog 
6'b101110: begin
  ara_req_d.op      = ara_pkg::VNCLIPU;
  ara_req_d.eew_vs2 = vtype_q.vsew.next();
end
```

2022-10-27 19:10 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +                unique case (vxrm)
I do not understand these rounding functions. Are you sure of these?

2022-10-27 19:10 UTC, mp-17 commented on hardware/src/lane/simd_alu.sv
> +                  2'b00: r = clip[0];
For example, with `vxrm == 2'b00`, shouldn't the rounding `r` be like:

`2'b00: r = (opa.w16[b][3:0] == '0) ? 1'b0 : clipu[opa.w16[b][3:0] - 1];`

2022-10-31 11:59 UTC, mp-17 commented
Feel free to ping me when the PR is ready for another round of reviews @M-Ijaz-10x :-)

2022-10-31 12:27 UTC, mp-17 commented
LGTM, thanks a lot for the changes! I am running a back-end flow now to verify that everything is okay.

2022-11-01 05:59 UTC, M-Ijaz-10x commented
@mp-17 is there any update on the back-end flow side?

2022-11-01 09:47 UTC, mp-17 commented
@M-Ijaz-10x the lane was implemented with no problems. I am waiting for the system: I think that max 6h and it will be over!

2022-11-01 15:22 UTC, mp-17 commented
Still ongoing, busy servers today - But I will ping you as soon as it's over.

2022-11-03 21:27 UTC, mp-17 commented
The frequency was slightly lowered, but it's just because of the larger lane. I will try to solve this, but the implementation should be okay from a back-end side!

2022-11-16 12:31 UTC, mp-17 commented
Hello @M-Ijaz-10x, you are verifying the rounding functions, right? 
Please ping me when everything is ready so that I can run the CI and the backend flow on the most updated system.

2022-11-25 12:21 UTC, M-Ijaz-10x commented
@mp-17 I have updated the rounding mode functions as well. You can now run the backend flow

2022-11-30 10:35 UTC, mp-17 commented
Thanks a lot, the flow is running now! We thought about it, and since the fixed-point support has a non-negligible impact on the area, we can have a parameter to enable or disable the instantiation of the related logic in the `alu` or `multiplier`. 
So that if you need it, you can instantiate it, otherwise you go without it.
I can parameterize it and issue a PR on your branch, would that be okay with you?

2022-11-30 10:39 UTC, mp-17 commented on hardware/src/lane/fixed_p_rounding.sv
> +    if (valid_i)
^ r does not have a default value when valid_i == 1'b0

2022-11-30 11:54 UTC, M-Ijaz-10x commented on hardware/src/lane/fixed_p_rounding.sv
> +    if (valid_i)
Added

2022-11-30 12:43 UTC, M-Ijaz-10x commented
> Thanks a lot, the flow is running now! We thought about it, and since the fixed-point support has a non-negligible impact on the area, we can have a parameter to enable or disable the instantiation of the related logic in the `alu` or `multiplier`. So that if you need it, you can instantiate it, otherwise you go without it. I can parameterize it and issue a PR on your branch, would that be okay with you?

Sure. Just let me know when you create a PR on our branch

2022-11-30 14:39 UTC, M-Ijaz-10x commented
> Thanks a lot, the flow is running now! We thought about it, and since the fixed-point support has a non-negligible impact on the area, we can have a parameter to enable or disable the instantiation of the related logic in the `alu` or `multiplier`. So that if you need it, you can instantiate it, otherwise you go without it. I can parameterize it and issue a PR on your branch, would that be okay with you?

2022-11-30 15:57 UTC, mp-17 commented on hardware/src/lane/simd_mul.sv
> +      assign vxsat.w64[l]   = |mul_res.w128[l][127:64];
BTW, I noticed this only now: we are never checking `vxsat` in the `VSMUL` tests. Shouldn't this be :
```verilog
assign vxsat.w64[l]   = &mul_res.w128[l][127:64] & r[0];
```

2022-11-30 17:44 UTC, mp-17 commented on hardware/src/lane/simd_mul.sv
> +      assign vxsat.w64[l]   = |mul_res.w128[l][127:64];
PR: https://github.com/10x-Engineers/ara/pull/224

2022-11-30 17:44 UTC, mp-17 commented
PR: https://github.com/10x-Engineers/ara/pull/224

2022-12-01 14:25 UTC, M-Ijaz-10x commented
@mp-17 CI checks are over :)

2022-12-01 21:29 UTC, mp-17 commented
The backend is almost over as well! If there are no surprises because of the rounding functions, I will merge immediately ;-)

2022-12-03 14:40 UTC, M-Ijaz-10x commented
@mp-17 any updates?

2022-12-04 16:23 UTC, mp-17 commented
We will need to tune the implementation to reach 1 GHz without exploding in area; since this is now parameterized, we can merge this and then think about how to tune it.

2022-12-04 16:25 UTC, mp-17 commented
If you solve the conflicts (for the last time, I promise :-)) I will merge immediately.

2022-12-04 16:42 UTC, M-Ijaz-10x commented
> If you solve the conflicts (for the last time, I promise :-)) I will merge immediately.

Done :)

2022-12-05 08:02 UTC, merged