[HW] Add support for vector mask instructions
pulp-platform/ara pull request #149
Opened 2022-10-08 12:47 UTC by M-Ijaz-10x

Add support for `vmsbf`, `vmsof`, `vmsif`, `viota` and `vid` vector mask instructions

## Changelog

### Fixed

- Test for `viota` vector mask instruction

### Added

- Support for `vmsbf`, `vmsof`, `vmsif`, `viota` and `vid` vector mask instructions

### Changed

- Tests for `vmsbf`, `vmsof`, `vmsif` and `vid` vector mask instructions

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-10-26 07:52 UTC, mp-17 commented
I see that this PR is still draft. Can I review it already? :-)

2022-10-26 09:50 UTC, M-Ijaz-10x commented
> I see that this PR is still draft. Can I review it already? :-)

Yes, your review will be helpful. We are reviewing the seq modules logic internally that's why it is still draft, as soon as it is done we'll open the PR

2022-10-26 14:11 UTC, mp-17 commented on apps/riscv-tests/isa/rv64uv/viota.c
> +  VLOAD_8(v1, 1, 0, 0, 1, 0, 0, 0, 1);
`viota.m` works on mask vectors, so the source bits should be packed. 
Something like this should work:

```c
void TEST_CASE1() {
  VSET(1, e8, m1);
  VLOAD_8(v1, 0b10001001);
  VSET(8, e8, m1);
  asm volatile("viota.m v2, v1");
  VCMP_U8(1, v2, 0, 1, 1, 1, 2, 2, 2, 2);
}

void TEST_CASE2() {
  VSET(1, e8, m1);
  VLOAD_8(v1, 0b10001001);
  VLOAD_8(v0, 0b11000111);
  VSET(8, e8, m1);
  VLOAD_8(v2, 0, 1, 2, 3, 4, 5, 6, 7);
  asm volatile("viota.m v2, v1, v0.t");
  VCMP_U8(2, v2, 0, 1, 1, 3, 4, 5, 1, 1);
}
```

2022-10-26 16:20 UTC, mp-17 requested changes
Thanks a lot for starting this PR! This is really useful.
I started a review, but I am not 100% sure I got the underlying strategy to execute the instructions (thus far, I focused on `VIOTA`). 

I saw that the `VIOTA` test has a mistake: the source of `viota.m` comes from a mask register, while the output register is a normal `vsew` one. Maybe the implementation was influenced by this interpretation of the specs since the `spike` test does not pass while the test run on Ara passes! If this is the case, many of my questions are useless since there was only a misunderstanding.

Let me know :-)

2022-10-28 07:56 UTC, M-Ijaz-10x commented
> Unrelated question and just for information: are you also working on `vcpop` and `vfirst`?
> 
> Let me know!

Yes! I am working on `vcpop` and `vfirst`.

2022-10-28 10:16 UTC, M-Ijaz-10x commented
@mp-17 the `vcpop`, `vfirst` and permute instructions (`vrgather`, `vrgatherei16`, `vcompress`) implementation is complete on my end, but first I am focusing on clearing these two open PRs, once these are clean then I will create the PRs for the mentioned instructions as well.

2022-10-28 11:11 UTC, mp-17 commented
That sounds great! Thank you very much @M-Ijaz-10x! Please, tell me if you need anything from my side for this

2022-11-07 07:16 UTC, M-Ijaz-10x commented on hardware/src/masku/seq_modules/op_seq.sv
> +          EW8 : alu_operand_seq = {alu_operand[127:120], alu_operand[63:56], alu_operand[111:104], alu_operand[47:40], alu_operand[95 :88], alu_operand[31:24] ,alu_operand[79:72], alu_operand[15:8],
I have used the shuffle/deshuffle functions in place of seq_moudles

2022-11-07 07:18 UTC, M-Ijaz-10x commented
@mp-17 I have made the requested changes.

2022-11-08 21:14 UTC, mp-17 commented
Thanks @M-Ijaz-10x, I will review them asap!

2022-11-16 12:33 UTC, mp-17 commented
I am still running the flow here, unluckily the last runs crashed. I start forwarding a partial review (just one comment) on some complaints from the synthesizer

2022-11-16 12:35 UTC, mp-17 requested changes
I am still waiting for the backend flow, but here's a complaint from the synthesizer.

2022-11-16 17:05 UTC, mp-17 requested changes

2022-11-16 17:05 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +                        i = NrLanes * DataWidth;
It seems that this way of exiting the loops does not please Synopsys.
Replacing line 445 `i = NrLanes * DataWidth;` 445 with `break` works

2022-11-20 15:49 UTC, mp-17 commented
The backend results seem okay here! There were just some complaints from Synopsys, reported above ^

2022-11-21 07:30 UTC, M-Ijaz-10x commented
@mp-17 I have made the requested changes

2022-11-21 09:18 UTC, mp-17 commented
@M-Ijaz-10x The CI seems broken because of the `Makefrag`: 
https://github.com/pulp-platform/ara/actions/runs/3512373226/jobs/5885023126#step:8:13

2022-11-21 09:57 UTC, M-Ijaz-10x commented
> @M-Ijaz-10x The CI seems broken because of the `Makefrag`: https://github.com/pulp-platform/ara/actions/runs/3512373226/jobs/5885023126#step:8:13

Fixed

2022-11-28 12:25 UTC, mp-17 approved these changes

2022-11-28 12:26 UTC, merged