add kernels: gemv, spmv, conjugate gradient
pulp-platform/ara pull request #175
Opened 2022-11-11 15:56 UTC by husterZC

Description of PR that completes issue here...

### Added

- spmv
- gemv
- conjugate gradient

2022-11-11 16:23 UTC, mp-17 commented
Thanks a lot @husterZC, I will check it asap!

2022-11-11 16:40 UTC, husterZC commented
Hi Matteo, one thing to notice: 

In the conjugate_gradient/shared_kernels. these are all soft link files, but I don't know why we I push them, they loss the link. Could you please fix them yourself, either make a hard copy or make a link file.  And for some workloads using other kernels, do you suggest to make a link or a hard copy?

2022-11-13 17:28 UTC, mp-17 commented
I would prefer symlinks to avoid duplicated code. I created a PR to your `main`: `https://github.com/husterZC/ara/pull/1`

2022-11-14 11:32 UTC, mp-17 requested changes
Thanks a lot for the contribution! 
Can you please pass everything through `clang-format` and adjust the vertical alignment in `apps/common/default_args.mk`?
Then, if the CI checks pass, LGTM!

2022-11-14 11:32 UTC, mp-17 commented on apps/common/default_args.mk
> +def_args_spmv				 = "128 128 0.6"
Please adjust vertical alignment ^

2022-11-14 11:32 UTC, mp-17 commented on apps/conjugate_gradient/main.c
> +	while(len>MAX_AVL){
Have you passed this through `clang-format`? 
To do so, just run `make -C apps format`

2022-11-22 11:24 UTC, mp-17 commented
@husterZC Ping me if you need support! :-)

2022-11-22 11:50 UTC, husterZC commented
To be honest, I'm busy on other stuff. I plan to fix this last in this week

2022-11-28 09:31 UTC, husterZC commented
Hey Matteo,

I've added the dependence of `sklearn` python package for conjugate gradient kernel.
We need this one to generate the symmetric and positive-defined (SPD) dense/sparse matrix for conjugate gradient
If you find it is a bit troublesome to add new dependency, there are other solutions:
1. I can bring a pre-build SPD matrix and delete the function to generate SPD matrix at given size and sparsity. Well that  would be very boring, and not very meaningful.
2. I can look into how to generate SPD matrix at given size and sparsity, drive myself to be a mathematician and take somedays of working.

2022-11-30 18:06 UTC, mp-17 commented
https://github.com/pulp-platform/ara/actions/runs/3563364133/jobs/5989785427#step:8:289

2022-12-02 10:25 UTC, husterZC commented
Hi Matteo, I wonder how to add the python package "sklearn" in the CI environment, otherwise it will always sticking here ;)

2023-06-26 14:54 UTC, mp-17 approved these changes

2023-12-02 11:25 UTC, closed without merging

2023-12-02 11:25 UTC, mp-17 commented
I will check everything and merge here -> https://github.com/pulp-platform/ara/pull/267
Thanks again Chi!