[HW] Add support for vcpop and vfirst instructions
pulp-platform/ara pull request #178
Opened 2022-11-17 05:03 UTC by M-Ijaz-10x

Added support for vector population count `vcpop` and vector find first set bit `vfirst` instructions

## Changelog

### Fixed

- N/A

### Added

- Support for vector population count `vcpop` and vector find first set bit `vfirst` instructions
- Test for  vector population count `vcpop` instruction

### Changed

- Test for find first set bit `vfirst` instruction

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-11-18 21:48 UTC, mp-17 requested changes
Thanks a lot for this PR! I am running the flow on this right now. 
In the meantime, the first round of reviews :-)

2022-11-18 21:48 UTC, mp-17 commented on hardware/src/ara.sv
> +    .pe_scalar_resp_valid_i(pe_req.op inside{[VCPOP:VFIRST]} ? result_scalar_valid : masku_operand_valid[0][1]), // MaskB OpQueue Valid
`result_scalar` and `result_scalar_valid` are not defined here ^

2022-11-18 21:48 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +  logic  [$clog2(DataWidth*NrLanes)-1:0] popcount, vfirst_count;
`logic [$clog2(DataWidth*NrLanes):0] popcount, vfirst_count;`

^ We can count up to `DataWidth*NrLanes`, included

2022-11-18 21:48 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +  logic  [11:0]                          popcount_d, popcount_q;
Why 12 bits? Shouldn't these depend on `vlen`? 
`logic [VLEN:0] popcount_d, popcount_q;`
`logic [VLEN-1:0] vfirst_count_d, vfirst_count_q;`

2022-11-18 21:48 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +  logic  [11:0]                          popcount_sum;
Dead code ^

2022-11-19 12:43 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +  logic  [11:0]                          popcount_sum;
(I mean -> `popcount_sum`)

2022-11-20 15:51 UTC, mp-17 commented
After addressing the comments above, LGTM and we can merge. The backend results are also okay!

2022-11-21 07:10 UTC, M-Ijaz-10x commented
@mp-17 I have made the requested changes

2022-11-21 23:10 UTC, mp-17 approved these changes

2022-11-28 12:35 UTC, M-Ijaz-10x commented
> Hello @M-Ijaz-10x, I merged the previous PR, thanks a lot for the work! Would you mind rebasing this branch on the new `main`? I will merge this afterward ;-)

Sure

2022-11-28 15:52 UTC, mp-17 commented
Was it rebased on our `main`? I still see `This branch cannot be rebased due to conflicts` on the interface

2022-11-28 15:54 UTC, M-Ijaz-10x commented
> Was it rebased on our `main`? I still see `This branch cannot be rebased due to conflicts` on the interface. Moreover, `rv64uv-ara-vmsbf` is failing

Yes it was rebased with `pulp-platform/ara/main`, I am figuring out the problem with the rebase which is causing `vmsbf` failure

2022-11-30 10:42 UTC, mp-17 commented
I will merge it as soon as the CI is over! Thanks again!

2022-11-30 16:13 UTC, M-Ijaz-10x commented
> I will merge it as soon as the CI is over! Thanks again!

CI checks are over

2022-11-30 18:04 UTC, merged