[HW] Add support for vfrsqrt7 instruction
pulp-platform/ara pull request #184
Opened 2022-11-29 14:16 UTC by Shafi10x

vfrsqrt7 is a unary vector-vector instruction that returns an estimate of 1/sqrt(x) accurate to 7 bit.
### Input
For the non-exceptional cases:
- If input is normal, normalized input exponent is equal to the input exponent and normalized input significand(mantissa) is equal to the input significand.
- If input is subnormal, normalized input exponent is equal to 0 minus the number of leading zeros in the signifcand and the normalized input significand is given by shifting the input significand left by 1 minus the normalized input exponent.
### Output
- Output exponent can be found by:
                exp_o = (3*B-1-exp_i )/2
                         where B is exponent bias.
- Output 7-bit significand can be found by using lookup table.
- The address of lookup table is found by concatenating last LSB of the normalized input exponent and the six MSBs of the normalized input significand.
- The remainder of the result significand is zero
- The output sign equals the input sign.
## Changelog

### Fixed

- N/A

### Added

- Added support for vfrsqrt7 instruction
- Added tests for vfrsqrt7 instruction

### Changed

- N/A

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-11-30 19:50 UTC, mp-17 requested changes
Thanks a lot for the contribution! I started looking at it and writing some comments while the tool is synthesizing and implementing.
Then, I will check the mathematical part with more attention.

2022-11-30 19:50 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +                operand_a_delay <=operand_a ;
Why are you delaying `operand_a` by one cycle? Is it because the `FPU` latency is 1 cycle for the `CLASSIFY` operation, and you need the source operand as well? 
If so, it would be better to parametrize this operation on the `LatFNonComp` parameter so that this instruction does not break when the parameter is tuned. You can have a look at https://github.com/pulp-platform/ara/blob/main/hardware/src/lane/simd_mul.sv#L71 for the "pipeline" creation.
This can keep full throughput for the operation, otherwise, you can also keep only one register to delay `operand_a` by 1 cycle regardless of the latency of the `CLASSIFY` op and simply mask the FPU input ready until you are not ready to buffer another `operand_a`, i.e. when you are over with the current result.

2022-11-30 19:50 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +             vfrsqrt7_out_e16[3] = vfrsqrt7_fp16(vfpu_result[57:48],operand_a_delay[63:48],lzc_e16[15:12]);
```verilog
for (int h = 0; h < 4; h++) vfrsqrt7_out_e16[h] = 
  vfrsqrt7_fp16(vfpu_result[h*16 +: 10], operand_a_delay[h*16 +: 16], lzc_e16[h*4 +: 4]);
```

2022-11-30 19:50 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +             vfrsqrt7_out_e32[1] = vfrsqrt7_fp32(vfpu_result[41:32],operand_a_delay[63:32],lzc_e32[9:5]);
```verilog
for (int w = 0; w < 2; w++) vfrsqrt7_out_e32[w] = 
  vfrsqrt7_fp32(vfpu_result[w*32 +: 10], operand_a_delay[w*32 +: 32], lzc_e32[w*5 +: 5]);
```

2022-11-30 19:50 UTC, mp-17 commented on hardware/src/lane/vmfpu.sv
> +            vfrsqrt7_out_e64 = vfrsqrt7_fp64(vfpu_result[9:0],operand_a_delay[63:0],lzc_e64[5:0]);
```verilog
for (int d = 0; d < 1; d++) vfrsqrt7_out_e64[d] = 
  vfrsqrt7_fp64(vfpu_result[d*64 +: 10], operand_a_delay[d*64 +: 64], lzc_e64[d*6 +: 6]);
```

2022-12-01 12:38 UTC, Shafi10x commented on hardware/src/lane/vmfpu.sv
> +                operand_a_delay <=operand_a ;
Should I need to change `vfpu_flag_mask` also?

2022-12-01 12:48 UTC, Shafi10x commented on hardware/include/ara_pkg.sv
> +localparam int unsigned E32_NaN   = 32'h7fc00000;
As it was used previously in the code that's why I used the same thing. I can change it `logic [31:0]` if you want.

2022-12-01 12:49 UTC, Shafi10x commented on apps/riscv-tests/isa/rv64uv/vfrsqrt7.c
> +// Author: Matteo Perotti <mperotti@iis.ee.ethz.ch>
Sure. :-)

2022-12-01 12:51 UTC, Shafi10x commented on hardware/include/ara_pkg.sv
> +          7'd20 : vfrsqrt7_lut_out=7'd30;
Yes.

2022-12-08 06:40 UTC, Shafi10x commented
@mp-17 I have updated all the changes according to your suggestions.

2022-12-10 12:31 UTC, mp-17 commented
Thanks a lot and sorry for the delay! I am checking rn!

2022-12-12 17:52 UTC, mp-17 requested changes
Okay, thanks a lot! It looks good; let's see the CI. 
Now, I will just 1) make some style changes and 2) parameterize these more "exotic" floating-point instructions since they are not optimized inside the FPU. I will then issue a PR on your `10x` fork with my changes. After the iteration, we can merge.

2022-12-14 13:13 UTC, Shafi10x commented on hardware/include/ara_pkg.sv
> +                                vfrsqrt7_exp_o = E64_3xB +(~vfrsqrt7_exp_i);
`vfrsqrt7_exp_i` is mux output, I mean it is not awlays `vfrsqrt7_exp_i = 12'd0 - {6'd0,leading_zeros_count};`. So, `vfrsqrt7_exp_o = E64_3xB + leading_zeros_count - 1;` is not possible.

2022-12-14 14:37 UTC, Shafi10x commented
>

2022-12-14 14:42 UTC, Shafi10x commented on hardware/include/ara_pkg.sv
> +                                vfrsqrt7_exp_o = E64_3xB +(~vfrsqrt7_exp_i);
I have also parametrized `vfpu_flag_mask` . I have tested `vfrsqrt7` and ` vfclass` both by changing  the parameter `LatFNonComp` value and it works fine.

2022-12-14 14:51 UTC, mp-17 commented on hardware/include/ara_pkg.sv
> +                                vfrsqrt7_exp_o = E64_3xB +(~vfrsqrt7_exp_i);
Thanks a lot! 

> `vfrsqrt7_exp_i` is mux output, I mean it is not awlays `vfrsqrt7_exp_i = 12'd0 - {6'd0,leading_zeros_count};`. So, `vfrsqrt7_exp_o = E64_3xB + leading_zeros_count - 1;` is not possible.

It should be possible by controlling the output mux with both `vfpu_result[6:5]` and `vfpu_result`, like

```verilog
case ({vfpu_result[6:5], vfpu_result}) 
  {2'b01, fpnew_pkg::POSNORM}: begin
    ...
  end
endcase
```

But I don't know if this is needed. And if we parametrize the support for this instruction, we can optimize it afterward with no problems.

2022-12-14 14:51 UTC, mp-17 commented
Let's wait for the CI, then! :-)

2022-12-15 08:14 UTC, Shafi10x commented on hardware/src/ara_dispatcher.sv
> +      if (ara_req_valid_d && (ara_req_d.op inside {VFRSQRT7}) && (FPExtSupport == FPExtSupportDisable))
Should this comment be like  `Check that we have vfrsqrt7 support..`?

2022-12-15 10:13 UTC, mp-17 commented on hardware/src/ara_dispatcher.sv
> +      if (ara_req_valid_d && (ara_req_d.op inside {VFRSQRT7}) && (FPExtSupport == FPExtSupportDisable))
Definitely, thanks! :-)

2022-12-22 14:32 UTC, mp-17 commented
I see there is a problem with the `riscv-tests-simv` job. Once it is solved and the branch is rebased, we can merge!

2022-12-26 10:56 UTC, Shafi10x commented
Can I get permission to run CI checks on this PR?

2022-12-27 14:39 UTC, Shafi10x commented
@mp-17  The CI checks have passed and all conflicts have resolved. Can we merge this?

2023-01-15 12:46 UTC, mp-17 commented
Yes, definitely! Can you please rebase? I will merge afterwards :-)

2023-01-16 13:38 UTC, mp-17 commented
I still see there are conflicts. Have you rebased on the current `main`? 
(sorry for this rebase ping-pong!)

2023-01-17 07:25 UTC, Shafi10x commented
@mp-17 Yesterday, I have resolved all the conflicts. I am not seeing any conflicts right now.

2023-01-17 09:43 UTC, mp-17 commented
I think you merged our `main` into the branch instead of rebasing it on top of `main`.

2023-01-18 05:54 UTC, Shafi10x commented
@mp-17 now this PR is ready for merging.

2023-01-20 14:41 UTC, Shafi10x commented
@mp-17 Can we merge this PR?

2023-01-20 14:47 UTC, mp-17 commented
Done, thank you again.

2023-01-20 14:47 UTC, merged