[HW] Add support for vfrec7 instruction
pulp-platform/ara pull request #191
Opened 2022-12-07 10:53 UTC by Shafi10x

vfrec7 is a unary vector-vector instruction that returns an estimate of 1/x accurate to 7 bit.
### Input
- Exceptional cases are according to table.
- For the non-exceptional cases:
  #### Normal
   - If the input is normal, normalized input exponent is equal to the input exponent and normalized input significand(mantissa) is equal to the input significand.
  #### Subnormal
  - If the input is subnormal, normalized input exponent is equal to 0 minus the number of leading zeros in the signifcand and the normalized input significand is given by shifting the input significand left by 1 minus the normalized input exponent.
  - For normalization only two MSBs bits of significand are considered for counting the number of leading zeros, all other bits are ignored according to table.
  - If the significand=01..., the number of leading zeros is 1. So, the normalized input exponent is equal to 0 minus 1 and the normalized input significand is given by shifting the input significand left by 2.
  - If the significand=1...., the number of leading zeros is 0. So, the normalized input exponent is equal to 0 and the normalized input significand is given by shifting the input significand left by 1.
  - If the significand=00..., the output is fixed either infinity or maximum magnitude depending upon rounding mode.
### Output
- Normalized output exponent can be found by:
                exp_o = 2*B-1-exp_i 
                         where B is exponent bias.
- Normalized output 7-bit significand can be found by using lookup table.
- The address of lookup table is found by the seven MSBs of the normalized input significand.
- The remainder of the result significand is zero.
- The output sign equals the input sign.
  #### Normal
  - If the output is normal, then the output exponent equals the normalized output exponent, and the output significand equals the normalized output significand.
  #### Subnormal
  - If the output is subnormal,then the output exponent is 0, and the output significand is given by concatenating a 1 bit to the left of the normalized output significand, then shifting that quantity right by 1 minus the normalized output exponent.
## Changelog

### Fixed

- N/A

### Added

- Added support for vfrec7 instruction
- Added tests for vfrec7 instruction

### Changed

- N/A

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2022-12-12 18:11 UTC, mp-17 requested changes
Thanks a lot for the contribution! It generally looks good; let's see the CI; I will make some style changes and parametrize the implementation since it's not optimized in the FPU. I also want to run a synthesis flow with a slightly larger lane and see if I can make both the new FP instructions fit.

Can I just ask you to verify that everything works (both for this and the `vfrsqrt7` instruction) also when `LatFNonComp` is changed?

2022-12-15 10:51 UTC, Shafi10x commented
Should I update `vfrec7` according to `vfrsqrt7`? i.e parametrize `vfrec7 `instruction.

2022-12-15 10:53 UTC, mp-17 commented
> Should I update `vfrec7` according to `vfrsqrt7`? i.e parametrize `vfrec7 `instruction.

It would be perfect, thank you very much!

2022-12-16 11:11 UTC, Shafi10x commented
I have parametrized vfrec7 instruction and also have aligned some piece of code.

2022-12-21 08:43 UTC, M-Ijaz-10x commented
@mp-17 The CI checks are clear. Can we merge this in or anything needs to be restructured?

2022-12-21 12:37 UTC, merged