[HW] Shift popcount logic for vcpop.m instruction to lanes
pulp-platform/ara pull request #198
Opened 2022-12-27 16:43 UTC by M-Ijaz-10x

Shifted `popcount` logic for `vcpop.m` instruction from mask unit to lanes

## Changelog

### Fixed

- N/A

### Added

- N/A

### Changed

- Shifted `popcount` logic for `vcpop.m` instruction from mask unit to lanes

## Checklist

- [x] Automated tests pass
- [x] Changelog updated
- [x] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2023-01-13 16:48 UTC, mp-17 commented
Thanks a lot @M-Ijaz-10x, the backend is running on this!

2023-01-15 12:37 UTC, mp-17 requested changes
I have reviewed the PR while the backend is running. Pushing the partial popcount to the lanes present some pitfalls I did not think of, let's see the backend results and decide what to do.

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +
This should work:

```verilog
  //////////////
  // POPCOUNT //
  //////////////

  logic [$clog2(DataWidth):0] popcount;

  // Population count for vcpop.m instruction
  popcount #(
    .INPUT_WIDTH (DataWidth)
  ) i_popcount (
    .data_i     ((!pe_req.vm) ? mask_operand_o[2] & mask_operand_o[0] : mask_operand_o[2]),
    .popcount_o (popcount                                                                )
  );

  assign vcpop_operand_o = elen_t'(popcount);
```

But I think we can also encode the partial popcount in `mask_operand_o[2]` to save all-to-all connections from the `MASKU`. 

```verilog
  `STRUCT_VECT(elen_t, [NrMaskFUnits+2-1:0]) mask_operand;

...

    .mask_operand_o                   (mask_operand[1:0]                  ),

...

    .mask_operand_o       (mask_operand[2 +: NrMaskFUnits]        ),

...

  //////////////
  // POPCOUNT //
  //////////////

  logic [$clog2(DataWidth):0] popcount;

  // Population count for vcpop.m instruction
  popcount #(
    .INPUT_WIDTH (DataWidth)
  ) i_popcount (
    .data_i     ((!pe_req_i.vm) ? mask_operand[2] & mask_operand[0] : mask_operand[2]),
    .popcount_o (popcount                                                          )
  );

  always_comb begin
    mask_operand_o = mask_operand;

    // During VCPOP,
    if (pe_req_i.op == VCPOP)
      mask_operand_o[2] = elen_t'(popcount);
  end
```

Somthing like this? ^

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +    .INPUT_WIDTH (DataWidth*NrLanes)
`DataWidth*NrLanes` -> `DataWidth`

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +    .popcount_o (vcpop_operand_o                                                         )
Wrong size for `vcpop_operand_o`

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +    .data_i     ((!pe_req.vm) ? mask_operand_o[2] & mask_operand_o[0] : mask_operand_o[2]),
Maybe this can lead to issues since `mask_operand_o[0]` and `mask_operand_o[2]` handshake independently in the `MASKU`. 
When executing a `POPC` operation, we can sync the two `valid` here in the lanes, e.g., by hiding the two `valid` if they are not both asserted.

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +    .data_i     ((!pe_req.vm) ? mask_operand_o[2] & mask_operand_o[0] : mask_operand_o[2]),
This also implies that the registers from which we fetch `mask_operand_o[0]` and `mask_operand_o[2]` should have the same encoding, i.e., they are shuffled with the same `eew`. 
Otherwise, the mask bits that target  `mask_operand_o[2]` in this lane can be in other lanes. 
Maybe we can inject a reshuffle operation before a `VCPOP` if the two registers have a different encoding.
Unluckily, pushing part of the vcpop tree into the lanes presents multiple issues, let's see if the effort is justified by the backend. Maybe with this run we will not close timing and we will need to pipeline the signal to the mask unit.

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/ara.sv
> +  elen_t     [NrLanes-1:0]                     vcpop_operand;
Is this signal really needed? Can't we encode the information in `mask_operand_o[2]`?

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/lane/lane.sv
> +
```verilog
  // vcpop.m variables

  pe_req_t pe_req;

  assign pe_req = pe_req_i;
```

^ can remove

2023-01-15 12:37 UTC, mp-17 commented on hardware/src/masku/masku.sv
> +        vcpop_operand[8*deshuffle_byte +: 8] = vcpop_operand_i[8*b +: 8];
If we encode the partial popcount in `masku_operand_a_i`, we can change this line to:

```verilog
vcpop_operand[8*deshuffle_byte +: 8] = alu_operand_a[8*b +: 8];
```

2023-01-16 10:11 UTC, M-Ijaz-10x commented
@mp-17 is the back-end flow over?

2023-01-16 12:26 UTC, mp-17 commented
Not yet. Unluckily, it crashed, but I have already restarted it. It won't take too long hopefully (tomorrow evening?)

2023-01-17 09:16 UTC, M-Ijaz-10x commented
@mp-17 Let me know when the back-end flow is over

2023-01-17 10:46 UTC, mp-17 commented
I don't have the full results yet, but the ones after placement are not great. The main problem is that we are stressing an interface path between lanes and an all-to-all connected unit (`masku`).
Initially, when I thought to push parts of the tree into the lanes, I thought about moving them to the lane's `valu`s, isolating the interface paths. 
But I see some criticalities: 1) the bit-wise mask should be applied before the `valu` since the unit does not receive it, 2) the `valu` should count ONLY the correct bits from `vstart` to `vl` that belong to that lane, 3) we should synchronize the mask and the bit vector to popcount, and 4) the mask should have the same encoding of the vector to popcount.

4) Is easy to solve: we just need to reshuffle one of the two if the encoding is different.
3) It should be easy enough. It's only a matter of modifying the handshake control in the `masku`.
1) We can apply the mask from the operand queue to the vector that is entering the `valu`.

Actually, I see 2) as more problematic. Each lane should know up to which bit to count and mask the other bits to zero, and this is something only the `masku` does.

We can try another (easier) approach. The main problem now is with the scalability of the system; 8 lanes already suffer from the popcount logic. How about keeping the whole tree in the mask unit like it was before this PR, but multi-cycling it?
The mask unit receives `NrLanes*DataWidth` bits and masks them appropriately. We can then feed a parametric popcount tree controlled by a counter, e.g., if the popcount tree is `NrLanes*DataWidth / 2` wide, it will take 2 cycles to complete a full sum and handshake the lanes. If we keep its instance parametric, we can also choose the best latency for the operation trading off the backend performance when scaling up the system.

2023-01-20 14:35 UTC, mp-17 commented
@M-Ijaz-10x, I will close this PR since we decided to chase a new implementation strategy.

2023-01-20 14:35 UTC, closed without merging