removing dependency to a specific gcc version
pulp-platform/ara pull request #25
Opened 2021-03-23 03:43 UTC by hossein1387

Description of PR that completes issue here...

## Changelog

### Fixed

- Removed dependency in Makefile to use a specific gcc version

### Added

- Used only `gcc` and `g++` commands so that the correct version is picked up by the build system

### Changed

- Used only `gcc` and `g++` commands so that the correct version is picked up by the build system

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2021-03-24 14:02 UTC, suehtamacv requested changes
Your changes look good to me, thanks for your contribution! Those are the compilers we use to compile GCC in our internal machines, this should not have been pushed to the open-source version of Ara.

I need a few stylistic changes before I can accept this PR. Could you please update the `CHANGELOG` file with your change? Also, we write our commit messages in the imperative tense, with a small tag indicating what does the commit change. For this commit, I imagine the `[Makefile]` tag would be appropriate.

2021-03-24 23:04 UTC, hossein1387 commented
> Your changes look good to me, thanks for your contribution! Those are the compilers we use to compile GCC in our internal machines, this should not have been pushed to the open-source version of Ara.
> 
> I need a few stylistic changes before I can accept this PR. Could you please update the `CHANGELOG` file with your change? Also, we write our commit messages in the imperative tense, with a small tag indicating what does the commit change. For this commit, I imagine the `[Makefile]` tag would be appropriate.

2021-03-25 08:48 UTC, mp-17 commented
> > Your changes look good to me, thanks for your contribution! Those are the compilers we use to compile GCC in our internal machines, this should not have been pushed to the open-source version of Ara.
> > I need a few stylistic changes before I can accept this PR. Could you please update the `CHANGELOG` file with your change? Also, we write our commit messages in the imperative tense, with a small tag indicating what does the commit change. For this commit, I imagine the `[Makefile]` tag would be appropriate.
> 
> Ok got it, I will add a commit tag.

Hello Hossein, thanks a lot for your contribution. 
The contribution guidelines are new, and maybe not completely clear: this is the first time we open the project to public, so please be patient with this commit stuff, I know it can be cumbersome :-) 
The main purpose is to have a clean history, in which each commit is meaningful and consistent. Since in this pull request you have modified the Makefile and the Changelog, one possible log could be composed of 2 commits:

`[Makefile] Remove dependency for a specific gcc version`
`[Changelog] Update changelog`

Keeping the imperative form for the first verb, and avoiding merges from external branches. One useful tool to achieve this history from the current state can be `git rebase -i`.

Let us know if you need more information, and thanks again for the patience! ;-)

2021-04-05 19:09 UTC, suehtamacv approved these changes
LGTM, thanks for your contribution @hossein1387!

2021-04-05 19:09 UTC, merged