Add VCU118 Support to mp/pulp-v1-os-fpga Branch
pulp-platform/ara pull request #362
Opened 2024-10-04 09:52 UTC by mrbilandi

This pull request integrates support for the Xilinx VCU118 FPGA platform into the mp/pulp-v1-os-fpga branch.

## Changelog

### Changes
cheshire/Makefile:

Modified to support any specified platform using BOARD=<desired-board>. For example, use "make ara-chs-xilinx BOARD=vcu118" to build for the VCU118 platform.

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

2024-10-04 10:18 UTC, aitesam961 commented
Nice work @mrbilandi were you able to run baremetal or OS on it?

2024-10-10 13:26 UTC, mp-17 requested changes
Thanks a lot! Once the questions are addressed, we can merge.

2024-10-10 13:26 UTC, mp-17 commented on Makefile
> +CLANG_CXX ?= clang++-14
We can drop this change, right?

2024-10-11 10:11 UTC, mrbilandi commented
Hi @aitesam961 
Yes, I was able to run. I think Matteo has plans to release the instructions.

2024-10-15 15:58 UTC, mp-17 commented
Hey @mrbilandi,

Since the base branch went out of sync due to flow modifications, I have pushed there your (adapted) commit and authored it with your username and email.

Everything is [here](https://github.com/pulp-platform/ara/pull/319/commits/7747bb0ab1a7540be87c1a13e25395f4940892da) in https://github.com/pulp-platform/ara/pull/319.

Let me know if this is okay for you and if I need to re-open this PR ;-)

2024-10-15 15:58 UTC, closed without merging