Merged PR: FP comparisons + conversions
pulp-platform/ara pull request #46
Opened 2021-06-22 13:45 UTC by mp-17

This is the merge of the pull requests https://github.com/pulp-platform/ara/pull/19 and https://github.com/pulp-platform/ara/pull/14

## Changelog

### Fixed

- Description of changes

### Added

- Description of changes

### Changed

- Description of changes

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

Please check our [contributing guidelines](CONTRIBUTING.md) before opening a Pull Request.

2021-06-24 15:51 UTC, mp-17 commented
Rebased after merging https://github.com/pulp-platform/ara/pull/40

2021-07-15 09:00 UTC, suehtamacv requested changes
Looks good, thanks Perotti. I have a few nitpicks, and I would also like to merge this PR after we merge #50, since that PR implements an improved and faster CI.

2021-07-15 09:00 UTC, suehtamacv commented on hardware/include/ara_pkg.sv
> -  localparam int unsigned LatMultiplierEW16 = 0;
I assume the critical path goes through this multiplier when synthesizing this Ara? Maybe another incremental compile run would allow us to remove it...

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/lane.sv
> +  spill_register #(
Vertical alignment. Please also use a more descriptive name for the instance. Maybe `i_mask_spill_register`?

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/lane_sequencer.sv
> +            operand_request_push[AluA] = (pe_req_i.use_vs1 && !(pe_req_i.op inside {[VMFEQ:VMFGE]})) ? 1'b1 : 1'b0;
No need to use a ternary operator.

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/lane_sequencer.sv
> +            operand_request_i[MulFPUA] = '{
Which instruction needs both the `Alu` and the `MulFPU` queues?

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/vector_fus_stage.sv
> +  assign mask_operand_o          = mask_operand_fu_i == MaskFUAlu  ? alu_mask_operand : mfpu_mask_operand;
Vertical alignment.

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/vector_fus_stage.sv
> +    .mask_operand_valid_o (alu_mask_operand_valid),
Vertical alignment.

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/vector_fus_stage.sv
> +    .mask_operand_valid_o (mfpu_mask_operand_valid),
Vertical alignment.

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/vmfpu.sv
> +  assign vinsn_issue_fpu = vinsn_issue_q.op inside {[VFADD:VFCVTFF], [VMFEQ:VMFGE]};
Could we rearrange the operations so that they are all contiguous?

2021-07-15 09:00 UTC, suehtamacv commented on hardware/src/lane/vmfpu.sv
> +    if (!vinsn_queue_full && vfu_operation_valid_i && (vfu_operation_i.vfu == VFU_MFpu || vfu_operation_i.op inside {[VMFEQ:VMFGE]})) begin
Please wrap the lines to 100 characters.

2021-08-05 09:33 UTC, mp-17 commented on hardware/src/lane/lane_sequencer.sv
> +            operand_request_i[MulFPUA] = '{
No one, indeed we push only in the correct opqueue: 

`if (pe_req_i.op inside {[VMFEQ:VMFGE]})` for the ALU

`if !(pe_req_i.op inside {[VMFEQ:VMFGE]})` for the VMFPU

2021-08-05 09:35 UTC, mp-17 commented on hardware/include/ara_pkg.sv
> -  localparam int unsigned LatMultiplierEW16 = 0;
Agree. Can we postpone this to the optimization phase? When the HW is more mature we can try to optimize the latency of the units. Or do you prefer to do it now?

2021-08-05 14:03 UTC, suehtamacv approved these changes
LGTM! Waiting for the CI.

2021-08-05 14:34 UTC, merged