Int red
pulp-platform/ara pull request #95
Opened 2022-01-11 18:14 UTC by mp-17

# Merge https://github.com/pulp-platform/ara/pull/92 before this one

Add integer reductions to Ara, and solve some related bugs.

## Changelog

### Fixed

- Description of changes

### Added

- Description of changes

### Changed

- Description of changes

## Checklist

- [ ] Automated tests pass
- [ ] Changelog updated
- [ ] Code style guideline is observed

2022-01-19 16:03 UTC, mp-17 commented
Ready for the review! ;-)

2022-03-10 11:51 UTC, suehtamacv requested changes
I have a few comments, but it looks nice. It is a key feature of Ara, nice to see it getting implemented! :tada:

2022-03-10 11:51 UTC, suehtamacv commented on hardware/src/lane/valu.sv
> +  assign alu_operand_a  = (alu_state_q == INTER_LANES_REDUCTION || alu_state_q == SIMD_REDUCTION || alu_state_q == INTRA_LANE_REDUCTION && !first_op_q)
`alu_state_q inside {INTER_LANES_REDUCTION, SIMD_REDUCTION, INTRA_LANE_REDUCTION}`

2022-03-10 11:51 UTC, suehtamacv commented on hardware/src/lane/valu.sv
> +  assign alu_operand_a  = (alu_state_q == INTER_LANES_REDUCTION || alu_state_q == SIMD_REDUCTION || alu_state_q == INTRA_LANE_REDUCTION && !first_op_q)
I think this deserves a comment as well..

2022-03-10 11:51 UTC, suehtamacv commented on hardware/src/lane/valu.sv
> +                endcase
`EW8 == 0`, right? Maybe you could replace this by a `3 - vinsn_issue_q.vtype.vsew`...

2022-03-26 15:55 UTC, mp-17 commented on hardware/src/lane/valu.sv
> +                endcase
I would say that the explicit notation I used is more immediate to understand, but no problems to change! ;-)

2022-03-26 15:59 UTC, mp-17 commented on hardware/src/lane/valu.sv
> +   endfunction: reduction_rx_cnt_init
Anyway: I also left the generic function to be used when the lanes do not have to be equal for PnR reasons

2022-03-27 11:19 UTC, suehtamacv approved these changes

2022-03-27 11:47 UTC, merged